//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysClientes.WcfTipoCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCliente", Namespace="http://schemas.datacontract.org/2004/07/WCF_CRUD")]
    [System.SerializableAttribute()]
    public partial class TipoCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetSetTICL_DESCRICAOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GetSetTICL_PK_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetSetTICL_TIPOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetSetTICL_DESCRICAO {
            get {
                return this.GetSetTICL_DESCRICAOField;
            }
            set {
                if ((object.ReferenceEquals(this.GetSetTICL_DESCRICAOField, value) != true)) {
                    this.GetSetTICL_DESCRICAOField = value;
                    this.RaisePropertyChanged("GetSetTICL_DESCRICAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GetSetTICL_PK_ID {
            get {
                return this.GetSetTICL_PK_IDField;
            }
            set {
                if ((this.GetSetTICL_PK_IDField.Equals(value) != true)) {
                    this.GetSetTICL_PK_IDField = value;
                    this.RaisePropertyChanged("GetSetTICL_PK_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetSetTICL_TIPO {
            get {
                return this.GetSetTICL_TIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.GetSetTICL_TIPOField, value) != true)) {
                    this.GetSetTICL_TIPOField = value;
                    this.RaisePropertyChanged("GetSetTICL_TIPO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfTipoCliente.IServiceTipoCliente")]
    public interface IServiceTipoCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoCliente/InsertTipoCliente", ReplyAction="http://tempuri.org/IServiceTipoCliente/InsertTipoClienteResponse")]
        string InsertTipoCliente(SysClientes.WcfTipoCliente.TipoCliente eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoCliente/InsertTipoCliente", ReplyAction="http://tempuri.org/IServiceTipoCliente/InsertTipoClienteResponse")]
        System.Threading.Tasks.Task<string> InsertTipoClienteAsync(SysClientes.WcfTipoCliente.TipoCliente eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoCliente/GetTipoCliente", ReplyAction="http://tempuri.org/IServiceTipoCliente/GetTipoClienteResponse")]
        System.Data.DataSet GetTipoCliente(SysClientes.WcfTipoCliente.TipoCliente eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoCliente/GetTipoCliente", ReplyAction="http://tempuri.org/IServiceTipoCliente/GetTipoClienteResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTipoClienteAsync(SysClientes.WcfTipoCliente.TipoCliente eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoCliente/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IServiceTipoCliente/FetchUpdatedRecordsResponse")]
        System.Data.DataSet FetchUpdatedRecords(SysClientes.WcfTipoCliente.TipoCliente eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoCliente/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IServiceTipoCliente/FetchUpdatedRecordsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(SysClientes.WcfTipoCliente.TipoCliente eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoCliente/UpdateTipoCliente", ReplyAction="http://tempuri.org/IServiceTipoCliente/UpdateTipoClienteResponse")]
        string UpdateTipoCliente(SysClientes.WcfTipoCliente.TipoCliente eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoCliente/UpdateTipoCliente", ReplyAction="http://tempuri.org/IServiceTipoCliente/UpdateTipoClienteResponse")]
        System.Threading.Tasks.Task<string> UpdateTipoClienteAsync(SysClientes.WcfTipoCliente.TipoCliente eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoCliente/DeleteTipoCliente", ReplyAction="http://tempuri.org/IServiceTipoCliente/DeleteTipoClienteResponse")]
        bool DeleteTipoCliente(SysClientes.WcfTipoCliente.TipoCliente eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoCliente/DeleteTipoCliente", ReplyAction="http://tempuri.org/IServiceTipoCliente/DeleteTipoClienteResponse")]
        System.Threading.Tasks.Task<bool> DeleteTipoClienteAsync(SysClientes.WcfTipoCliente.TipoCliente eDatils);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTipoClienteChannel : SysClientes.WcfTipoCliente.IServiceTipoCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTipoClienteClient : System.ServiceModel.ClientBase<SysClientes.WcfTipoCliente.IServiceTipoCliente>, SysClientes.WcfTipoCliente.IServiceTipoCliente {
        
        public ServiceTipoClienteClient() {
        }
        
        public ServiceTipoClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTipoClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertTipoCliente(SysClientes.WcfTipoCliente.TipoCliente eDatils) {
            return base.Channel.InsertTipoCliente(eDatils);
        }
        
        public System.Threading.Tasks.Task<string> InsertTipoClienteAsync(SysClientes.WcfTipoCliente.TipoCliente eDatils) {
            return base.Channel.InsertTipoClienteAsync(eDatils);
        }
        
        public System.Data.DataSet GetTipoCliente(SysClientes.WcfTipoCliente.TipoCliente eDatils) {
            return base.Channel.GetTipoCliente(eDatils);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTipoClienteAsync(SysClientes.WcfTipoCliente.TipoCliente eDatils) {
            return base.Channel.GetTipoClienteAsync(eDatils);
        }
        
        public System.Data.DataSet FetchUpdatedRecords(SysClientes.WcfTipoCliente.TipoCliente eDatils) {
            return base.Channel.FetchUpdatedRecords(eDatils);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(SysClientes.WcfTipoCliente.TipoCliente eDatils) {
            return base.Channel.FetchUpdatedRecordsAsync(eDatils);
        }
        
        public string UpdateTipoCliente(SysClientes.WcfTipoCliente.TipoCliente eDatils) {
            return base.Channel.UpdateTipoCliente(eDatils);
        }
        
        public System.Threading.Tasks.Task<string> UpdateTipoClienteAsync(SysClientes.WcfTipoCliente.TipoCliente eDatils) {
            return base.Channel.UpdateTipoClienteAsync(eDatils);
        }
        
        public bool DeleteTipoCliente(SysClientes.WcfTipoCliente.TipoCliente eDatils) {
            return base.Channel.DeleteTipoCliente(eDatils);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTipoClienteAsync(SysClientes.WcfTipoCliente.TipoCliente eDatils) {
            return base.Channel.DeleteTipoClienteAsync(eDatils);
        }
    }
}
