--LISTA OS CLIENTES
CREATE PROCEDURE dbo.CLIENTE_LISTA  
	@ID INT = NULL  
AS  
BEGIN  
	SELECT CLIE.CLIE_PK_ID, CLIE.CLIE_CPF, CLIE.CLIE_NOME, Convert(varchar(12), CLIE.CLIE_NASCIMENTO, 103) CLIE_NASCIMENTO, CLIE.CLIE_SEXO
	, TICL.TICL_TIPO, CLIE.CLIE_FK_PK_TICL, TICL.TICL_DESCRICAO, CLIE.CLIE_FK_PK_SICL, SICL.SICL_DESCRICAO
	FROM DBO.CLIENTES CLIE
		LEFT JOIN DBO.TIPO_CLIENTES TICL  
			ON CLIE.CLIE_FK_PK_TICL = TICL.TICL_PK_ID  
		LEFT JOIN DBO.SITUACAO_CLIENTES SICL
			ON CLIE.CLIE_FK_PK_SICL = SICL.SICL_PK_ID
	WHERE CLIE.CLIE_PK_ID = ISNULL(@ID, CLIE.CLIE_PK_ID)  
END 

GO 

--LISTA SITUACAO_CLIENTES
CREATE PROCEDURE SITUACAO_CLIENTES_LISTA 
	@ID INT = NULL  
AS  
BEGIN 
	SELECT *
	FROM DBO.SITUACAO_CLIENTES
	WHERE SICL_PK_ID = ISNULL(@ID, SICL_PK_ID)  
END

GO

--LISTA TIPO_CLIENTES
CREATE PROCEDURE LISTA_TIPO_CLIENTES  
	@ID INT = NULL  
AS  
BEGIN 
	SELECT *
	FROM DBO.TIPO_CLIENTES
	WHERE TICL_PK_ID = ISNULL(@ID, TICL_PK_ID)  
END

GO

--INSERI CLIENTE
CREATE PROCEDURE CLIENTE_INSERT  
	@CPF VARCHAR(15),  
	@NOME VARCHAR(100),  
	@NASCIMENTO DATETIME,
	@SEXO CHAR(1),
	@TIPO_CLIENTE INT,  
	@SITUACAO_CLIENTE INT
AS  
BEGIN  
	INSERT INTO [DBO].[CLIENTES]
           ([CLIE_CPF]
           ,[CLIE_NOME]
           ,[CLIE_NASCIMENTO]
           ,[CLIE_SEXO]
           ,[CLIE_FK_PK_TICL]
           ,[CLIE_FK_PK_SICL])
     VALUES (@CPF, @NOME, @NASCIMENTO, @SEXO, @TIPO_CLIENTE, @SITUACAO_CLIENTE)
END 

GO

--INSERI SITUACAO CLIENTE
CREATE PROCEDURE SITUACAO_CLIENTE_INSERT
	@DESCRICAO VARCHAR(100)
AS
BEGIN
	INSERT INTO [DBO].[SITUACAO_CLIENTES] ([SICL_DESCRICAO])
    VALUES (@DESCRICAO)
END

GO

--INSERI TIPO DE CLIENTE
CREATE PROCEDURE TIPO_CLIENTE_INSERT
	@TIPO Varchar(50),
	@DESCRICAO VARCHAR(100)
AS
BEGIN
	INSERT INTO [DBO].[TIPO_CLIENTES] ([TICL_TIPO], [TICL_DESCRICAO])
     VALUES (@TIPO, @DESCRICAO)
END

GO

--ALTERA CLIENTE
CREATE PROCEDURE CLIENTE_UPDATE  
	@ID INT,  
	@CPF VARCHAR(15),  
	@NOME VARCHAR(100),  
	@NASCIMENTO DATETIME,
	@SEXO CHAR(1),
	@TIPO_CLIENTE INT,  
	@SITUACAO_CLIENTE INT 
AS  
BEGIN  
	UPDATE DBO.CLIENTES SET  
		CLIE_CPF = @CPF,  
		CLIE_NOME = @NOME,  
		CLIE_NASCIMENTO = @NASCIMENTO,
		CLIE_SEXO = @SEXO,
		CLIE_FK_PK_TICL = @TIPO_CLIENTE,  
		CLIE_FK_PK_SICL = @SITUACAO_CLIENTE  
	WHERE CLIE_PK_ID = @ID
END

GO 

--ALTERA SITUACAO CLIENTE
CREATE PROCEDURE SITUACAO_CLIENTE_UPDATE
	@ID INT,
	@DESCRICAO VARCHAR(100)
AS
BEGIN
	UPDATE DBO.SITUACAO_CLIENTES SET
		SICL_DESCRICAO = @DESCRICAO
	WHERE SICL_PK_ID = @ID
END 

GO

--ALTERA TIPO DE CLIENTE
CREATE PROCEDURE TIPO_CLIENTE_UPDATE
	@ID INT,
	@TIPO CHAR(50),
	@DESCRICAO VARCHAR(100)
AS
BEGIN
	UPDATE DBO.TIPO_CLIENTES SET
		TICL_TIPO = @TIPO
		,TICL_DESCRICAO = @DESCRICAO
    WHERE TICL_PK_ID = @ID
END

GO

--EXCLUI CLIENTE
CREATE PROCEDURE CLIENTE_DELETE  
	@ID INT  
AS  
BEGIN  
	DELETE FROM CLIENTES  
	WHERE CLIE_PK_ID = @ID  
END

GO

--EXCLUI SITUAÇÃO CLIENTE
CREATE PROCEDURE SITUACAO_CLIENTE_DELETE  
	@ID INT  
AS  
BEGIN  
	DELETE FROM SITUACAO_CLIENTES  
	WHERE SICL_PK_ID = @ID  
END

GO

--EXCLUI TIPO CLIENTE
CREATE PROCEDURE TIPO_CLIENTE_DELETE  
	@ID INT  
AS  
BEGIN  
	DELETE FROM TIPO_CLIENTES  
	WHERE TICL_PK_ID = @ID  
END

 